version: '2'
services:
  jhipstersampleapplication3-app:
    image: jhipstersampleapplication3
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplication3-mysql:3306/jhipstersampleapplication3?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8083:8083
  jhipstersampleapplication3-mysql:
    extends:
      file: mysql.yml
      service: jhipstersampleapplication3-mysql
